fixed for node 14
jaredwray/cacheable-request pull request #126
Opened 2022-06-03 09:50 UTC by alphmth

2022-06-03 15:23 UTC, jaredwray requested changes
@alphmth - thanks for sending this in. Can you look at the changes I asked for.

2022-06-03 15:23 UTC, jaredwray commented on .github/workflows/tests.yaml
> +        node: ['14', '16']
@alphmth - can you do 12, 14, and 16?

2022-06-03 15:23 UTC, jaredwray commented on package.json
> +		"test": "nyc ava",
@alphmth - did you remove it because of errors? If so, we will need to bring it back and upgrade it to latest. You can do that in another pull request.

2022-06-03 15:23 UTC, jaredwray commented on package.json
>  		"node": ">=8"
please move this to node 12

2022-06-03 15:23 UTC, jaredwray commented on test/cache.js
> +const { request } =require('http');
@alphmth - can you do proper spacing on the `=require`

2022-06-03 15:23 UTC, jaredwray commented on test/cache.js
> +		undefined,
@alphmth - why would we want to remove this? Wouldnt we want this cache error? Will this break others peoples code?

2022-06-03 16:47 UTC, alphmth commented on package.json
> +		"test": "nyc ava",
Yes I get this error so I removed it.

```
 test/cache.js:12:22
  ✖  12:22  Unable to resolve path to module ava.  import/no-unresolved

  test/cacheable-request-class.js:2:22
  ✖   2:22  Unable to resolve path to module ava.  import/no-unresolved

  test/cacheable-request-instance.js:6:22
  ✖   6:22  Unable to resolve path to module ava.  import/no-unresolved

````

2022-06-03 16:49 UTC, jaredwray commented on package.json
> +		"test": "nyc ava",
ok ... can you put in the es ignore on those lines?

2022-06-03 16:50 UTC, alphmth commented on test/cache.js
> +		undefined,
@jaredwray this `CacheableRequest.CacheError` is of function type so `throwsAsync` 2nd argument return error and suggest to pas undefined. this is [t.throwsAsync](https://github.com/avajs/ava/blob/main/docs/03-assertions.md#throwsasyncthrower-expectation-message) documentation

2022-06-04 17:01 UTC, jaredwray requested changes
@alphmth - let me know if you have any other questions

2022-06-06 09:03 UTC, alphmth commented
@jaredwray On node 12 I am getting this exception

```
internal/modules/cjs/loader.js:804
  throw new ERR_REQUIRE_ESM(filename);
  ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/development/projects/david/cacheable-request/node_modules/ava/entrypoints/cli.mjs
    at Module._extensions..mjs (internal/modules/cjs/loader.js:804:9)
    at Object.<anonymous> (/Users/development/projects/david/cacheable-request/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11

```

I tried looking at ava documentation they said to change extensions config to `js` but it gives the same error.

```

	"ava": {
		"extensions": [
			"js"
		]
	},

```

 By default, Ava is configured to use `esm` but we are using `commonjs`.

2022-06-06 09:46 UTC, alphmth commented
@jaredwray I think we can not use latest ava with node 12

https://github.com/avajs/ava/discussions/3005

2022-06-06 18:00 UTC, alphmth commented
> [#126 (comment)](https://github.com/jaredwray/cacheable-request/pull/126#issuecomment-1146045979)
> 
> @alphmth - here is the line of code to get coverage for: https://app.codecov.io/gh/jaredwray/cacheable-request/compare/126/changes

@jaredwray can you tell me what does `requestError` field for? There is a `Promise.race` before this and that always resolves 2nd promise first. Do you have idea how can I test this?

2022-06-06 18:04 UTC, jaredwray commented
> > [#126 (comment)](https://github.com/jaredwray/cacheable-request/pull/126#issuecomment-1146045979)
> > @alphmth - here is the line of code to get coverage for: https://app.codecov.io/gh/jaredwray/cacheable-request/compare/126/changes
> 
> @jaredwray can you tell me what does `requestError` field for? There is a `Promise.race` before this and that always resolves 2nd promise first. Do you have idea how can I test this?

@alphmth  are you believing that this will never execute? If so, then it should be removed. Can you validate that it never gets executed? If so, go ahead and remove it.

2022-06-07 00:52 UTC, jaredwray approved these changes

2022-06-07 00:53 UTC, merged