fixed hooks instance issue
jaredwray/cacheable-request pull request #167
Opened 2022-08-22 11:05 UTC by alphmth

Fixes #165

2022-08-23 17:03 UTC, jaredwray commented
Thanks for trying this but I think the better option is to finally make cacheable request a class and run hooks like we were planning. 

Let's go ahead and make that change to move it to a class and hooks part of that instance. 

How compatible would `got` be if we moved to a class architecture instead of a function. @szmarczak - would love your input here.

2022-08-27 21:32 UTC, jaredwray requested changes

2022-08-27 21:32 UTC, jaredwray commented on package.json
> +			"no-mixed-spaces-and-tabs": 0,
@alphmth - can you remove this and fix the file to support just tabs as we have done. You can also try to run `npx xo --fix`

2022-08-27 21:32 UTC, jaredwray commented on README.md
> -const cacheableRequest = CacheableRequest(request, cache);
@alphmth - please go over the entire README and make sure we have the new way this works with the breaking change documented. 

Example would be how you import this in your statement moving forward.

2022-08-27 21:32 UTC, jaredwray commented on src/types.ts
> +// Type definitions for cacheable-request 6.0
@alphmth - why would we need this file and definition? Shouldnt this be auto generated by typescript?

2022-08-27 21:32 UTC, jaredwray commented on src/index.ts
> +	hooks: Map<string, any> = new Map<string, any>();
@alphmth - shouln't we specify that instead of `any` it has to be a function?

2022-08-27 21:32 UTC, jaredwray commented on test/cacheable-request-instance.test.ts
> +	const cacheableRequest = new CacheableRequest(request, 'sqlite://non/existent/database.sqlite').createCacheableRequest();
@alphmth - is this the new standard on how this should work? Seems like this will be confusing if we dont document this.

2022-08-28 08:49 UTC, alphmth commented on test/cacheable-request-instance.test.ts
> +	const cacheableRequest = new CacheableRequest(request, 'sqlite://non/existent/database.sqlite').createCacheableRequest();
@jaredwray yes this is the new standard.

2022-08-28 08:49 UTC, alphmth commented on src/types.ts
> +// Type definitions for cacheable-request 6.0
@jaredwray I am importing the types from file to use it in main file. That is why i need this

2022-08-28 09:10 UTC, alphmth commented on README.md
> -const cacheableRequest = CacheableRequest(request, cache);
@jaredwray Do I need to add `breaking changes` heading and then explain?

2022-08-28 16:57 UTC, jaredwray commented on README.md
> -const cacheableRequest = CacheableRequest(request, cache);
Yes. please do.

2022-08-29 13:36 UTC, jaredwray approved these changes

2022-09-04 15:34 UTC, merged